### ISSUE TITLE
Define aplication functions

### ISSUE THREAD

**Issue by jmoralesg** [chingu-voyages/v17-chimeras-team-01#11]
Identify which are needs and which are wants

**Comment by jmoralesg** [comment]
Needs: 
* Store tabs temporarily
    * Need: 
        * store it for at least a session 
        * Have the option to easily remove links 
            * Have the option to move them up and down by dragging the links 
    * Want: store for longer
*  have the option to categorised them
    * Need: Have the option to choose between a list of provided categories 
    * Want: To add a category the prefer

Wants: 
* Maybe give the user the estimate amount of time since they decide it to store so they may consider removing it from the list
    * Needs: display the hrs the tab has been stored for 
    * Wants: send notifications to remain user that links are in the list to be reviewed

**Comment by webiroha** [comment]
About this, I think to use this spreadsheet is easier to understand.
What do you think?
https://docs.google.com/spreadsheets/d/1p8JRqimUm8jV7DbRqn1vxA3a8Z7N9B8NnuZeX7aABYc/edit#gid=1364712022

After defined each task of MVP, I will create each backlog with assigners and estimates.

**Comment by jmoralesg** [comment]
User Stories
 Define the attributes and roles of your end users and match them to your features and functions. This helps ensure that the app will have a logical flow, and more importantly, that it meets all user needs.
- I WANT TO remove tabs that I do not need while working on specific tasks SO I do not get distracted
- I WANT TO store the tabs I am not using temporarily SO I can go through them when I have the time or when I need them 
- I WANT TO organised the tabs in categories SO when I need them I can quickly find them

*Extras 
- I WANT TO add some tabs to my bookmarks SO I can always have them 
- I WANT TO have the top sites displayed first SO my workflow is faster
- I WANT TO restore tabs from a browsing session SO if by accident I close the browser I can still have them available

**Comment by webiroha** [comment]
@jmoralesg 
Thank you for the user stories.
Is it possible to add to spreadsheet them or associate with functions by writing down?
https://docs.google.com/spreadsheets/d/1p8JRqimUm8jV7DbRqn1vxA3a8Z7N9B8NnuZeX7aABYc/edit#gid=1364712022
I tried to associate them, but I could not find some you are showing which are related to the function.

**Comment by jmoralesg** [comment]
don't worry about that they all match the the two features
