### ISSUE TITLE
Product manager

### ISSUE THREAD

**Issue by webiroha** [chingu-voyages/v17-chimeras-team-01#16]
Keiko will mainly organize data, topics, etc
Let's do regarding the other things in turns.
OK?

**Comment by jmoralesg** [comment]
when you talk about data, is it like databases? and other "things" ?? would you mind being more specific what is it that you want to do?

**Comment by webiroha** [comment]
Sorry, I did not make it clear.

Below article is saying, 
"The Agile Project Manager (APM) is responsible for planning, leading, organizing, and motivating agile project teams. "
https://managedagile.com/agile-project-manager-job-description/

I meant that I will "organize tasks".
