### ISSUE TITLE
Do you want to do the rep for Pull Request?

### ISSUE THREAD

**Issue by webiroha** [chingu-voyages/v17-chimeras-team-01#17]
it might be better that someone to do it than Keiko because I am tier 1.

**Comment by jmoralesg** [comment]
I am tier one as well and to be able to add code to the project you might want to learn how to do it, I just did by watching this, it might help you too. 
https://www.youtube.com/watch?v=For9VtrQx58

**Comment by webiroha** [comment]
Sorry, I have confused about it as code reviewer and merge rep.
https://github.com/chingu-voyages/v17-chimeras-team-01/issues/18
I will close this.
