### ISSUE TITLE
Decide the code reviewer

### ISSUE THREAD

**Issue by webiroha** [chingu-voyages/v17-chimeras-team-01#18]
Keiko will review about CSS, HTML.
May I ask you to review JS you two?

**Comment by jmoralesg** [comment]
I think the dynamic we have already decided is  we all review everyones code

**Comment by webiroha** [comment]
Oh, I have misunderstood, sorry.
I see.
Does it mean one pull request will be reviewed by two?
After that, might be good to be merged by the last reviewer for efficiency if need to merge and the code is no problem.
