### ISSUE TITLE
About mock up tools

### ISSUE THREAD

**Issue by webiroha** [chingu-voyages/v17-chimeras-team-01#19]
### Figma (+ drawing)

might be good to use it because to share the prototype is easy and we can adjust and edit it each other for free.
Actually, most people use this and it has compatible. 
If not, we can change others.
What do you think?
Try to see below.

[Our team's prototype]
https://www.figma.com/file/vJicarh6O9dyz8PX1bzhRq/chimeras-team-01?node-id=0%3A2	

*this issue will be change for checking prototypes.
Don't close this!

### MVP for now (until 16th)
How much can we do it?
##### 1.most minimum
https://www.figma.com/proto/vJicarh6O9dyz8PX1bzhRq/chimeras-team-01?node-id=4%3A7&viewport=702%2C290%2C0.9320870041847229&scaling=min-zoom

##### 2.bit rich
https://www.figma.com/proto/vJicarh6O9dyz8PX1bzhRq/chimeras-team-01?node-id=20%3A82&viewport=383%2C329%2C0.09216661751270294&scaling=min-zoom

##### 3.other looks
https://www.figma.com/proto/vJicarh6O9dyz8PX1bzhRq/chimeras-team-01?node-id=27%3A62&viewport=1034%2C208%2C0.24644899368286133&scaling=min-zoom

**Comment by jmoralesg** [comment]
minimum is good for now

**Comment by webiroha** [comment]
I see.
Tell me if you have anything better ideas :)
This is for the discussion.
But I am not sure this minimum is efficient to create.

Text, drawing, direct correct, whichever is OK.
I will explain to you how to use Figma(if it is OK to use it) by screen share if you want.

I will continue to create some MVP as a base from sprint 3 to 5 for this bookmark if we continue.
If not, I will put one product on which is cloned for discussion.
