### ISSUE TITLE
Q. How long will you work on this voyage per week?

### ISSUE THREAD

**Issue by webiroha** [chingu-voyages/v17-chimeras-team-01#4]
**Answer**
Jo: __h
Jinyoung: __h
Keiko: 20h(2 - 3h per day)

**Comment by jmoralesg** [comment]
I am not sure, it will depending on the day an week, but initially 1-2h

**Comment by webiroha** [comment]
> I am not sure, it will depending on the day an week, but initially 1-2h

Does it mean per week?
It is OK, I want to grasp the estimated time so that we can build MVP certainly.
↓

Jo: 1-2h
Jinyoung: __h
Keiko: 20h(2 - 3h per day)

**Comment by jypark0407** [comment]
Probably 1-2 hour a day, but it can be more than that depending on the need. For now, I'll say 10 hour - 20 hour/week.
