### ISSUE TITLE
Q.Which mockup tools tool do you prefer? (XD, Invision, etc)

### ISSUE THREAD

**Issue by webiroha** [chingu-voyages/v17-chimeras-team-01#5]
**Answer**
Jo: 
Jinyoung: 
Keiko: (I created the earlier mock by sketch but whichever is OK) 

**reference:**
[mockup tool](https://docs.chingu.io/techres/mockuptools)

**Comment by jypark0407** [comment]
I'm also okay with anything. I've used Sketch and Balsamiq before. I think Sketch is quite useful and is the most commonly used prototyping tool.

**Comment by jmoralesg** [comment]
I haven't done prototyping or wire framing, so you might have to cope some hand drawing  :zany_face:
