### ISSUE TITLE
Q.Do we assign a project manager?

### ISSUE THREAD

**Issue by webiroha** [chingu-voyages/v17-chimeras-team-01#7]
**Answer**
Jo: 
Jinyoung: 
Keiko: I guess whichever we can work well.

**Comment by jypark0407** [comment]
**Answer**
Jo:
Jinyoung:I think we can either assign one or even get to do the rotation to try as project managers. 
Keiko: I guess whichever we can work well.

**Comment by webiroha** [comment]
**Answer**
Jo:
Jinyoung:I think we can either assign one or even get to do the rotation to try as project managers. 
Keiko: Might be good to take this role for me because I have more time than you two.
If it is no problem, I will do it.

**Comment by jmoralesg** [comment]
I am easy with either  option I think for the size of the project and the team we do not need to have a project manager, although I like the rotation idea, and if Keiko wants to have a go, do it, I support you :thumbsup:
